/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feedback;

/**
 *
 * @author Lenovo
 */
public class admin_choosetypes extends javax.swing.JFrame {

    /**
     * Creates new form admin_choosetypes
     */
    public admin_choosetypes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        update_fac = new javax.swing.JButton();
        delete_fac = new javax.swing.JButton();
        fac_performancs = new javax.swing.JButton();
        cantten_performance = new javax.swing.JButton();
        event_performance = new javax.swing.JButton();
        lib_performance = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 3, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("YOUR VOICE - YOUR CHOICE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 440, 60));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 600, 30));

        update_fac.setBackground(new java.awt.Color(153, 255, 0));
        update_fac.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        update_fac.setText("UPDATE FACULTY");
        update_fac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_facActionPerformed(evt);
            }
        });
        jPanel1.add(update_fac, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 220, 30));

        delete_fac.setBackground(new java.awt.Color(153, 255, 0));
        delete_fac.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        delete_fac.setText("DELETE FACULTY");
        delete_fac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_facActionPerformed(evt);
            }
        });
        jPanel1.add(delete_fac, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 220, 30));

        fac_performancs.setBackground(new java.awt.Color(255, 153, 153));
        fac_performancs.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        fac_performancs.setText("FACULTY PERFORMANCE");
        fac_performancs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fac_performancsActionPerformed(evt);
            }
        });
        jPanel1.add(fac_performancs, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 260, 30));

        cantten_performance.setBackground(new java.awt.Color(255, 153, 153));
        cantten_performance.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        cantten_performance.setText("CANTEEN PERFORMANCE");
        cantten_performance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantten_performanceActionPerformed(evt);
            }
        });
        jPanel1.add(cantten_performance, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 260, 30));

        event_performance.setBackground(new java.awt.Color(255, 153, 153));
        event_performance.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        event_performance.setText("EVENT PERFORMANCE");
        event_performance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                event_performanceActionPerformed(evt);
            }
        });
        jPanel1.add(event_performance, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 230, 30));

        lib_performance.setBackground(new java.awt.Color(255, 153, 153));
        lib_performance.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        lib_performance.setText("LIBRARY PERFORMANCE");
        lib_performance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lib_performanceActionPerformed(evt);
            }
        });
        jPanel1.add(lib_performance, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 240, 30));

        back.setBackground(new java.awt.Color(255, 255, 0));
        back.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 130, 40));

        jTextField1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jTextField1.setText("  TO VIEW PERFORMANCE : -");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 290, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 600, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feedback/b61f5ca67ca48af01b690db94a9b5413.jpgyellw.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void update_facActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_facActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
         new modifyfac().setVisible(true);
    }//GEN-LAST:event_update_facActionPerformed

    private void delete_facActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_facActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
         new deletefac().setVisible(true);
    }//GEN-LAST:event_delete_facActionPerformed

    private void fac_performancsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fac_performancsActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
         new faculty_performance().setVisible(true);
    }//GEN-LAST:event_fac_performancsActionPerformed

    private void cantten_performanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantten_performanceActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
         new canteenperformance().setVisible(true);
    }//GEN-LAST:event_cantten_performanceActionPerformed

    private void event_performanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_event_performanceActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
         new event_prformance().setVisible(true);
    }//GEN-LAST:event_event_performanceActionPerformed

    private void lib_performanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lib_performanceActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
         new library_performance().setVisible(true);
    }//GEN-LAST:event_lib_performanceActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
         new welcome().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_choosetypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_choosetypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_choosetypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_choosetypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_choosetypes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton cantten_performance;
    private javax.swing.JButton delete_fac;
    private javax.swing.JButton event_performance;
    private javax.swing.JButton fac_performancs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton lib_performance;
    private javax.swing.JButton update_fac;
    // End of variables declaration//GEN-END:variables
}
