/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feedback;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.Statement;
/**
 *
 * @author Lenovo
 */
public class canteen_feedbackform extends javax.swing.JFrame {

    /**
     * Creates new form canteen_feedbackform
     */
    public canteen_feedbackform() {
        initComponents();
        rating.setVisible(false);
        performance.setVisible(false);
        jTextField6.setVisible(false);
        jTextField7.setVisible(false);
        jTextField3.setVisible(false);       
        jTextField4.setVisible(false);        
        jTextField5.setVisible(false);
        jTextField8.setVisible(false);
        jTextField9.setVisible(false);
        jTextField10.setVisible(false);        
        jTextField11.setVisible(false);
        jTextField12.setVisible(false);
        jTextField13.setVisible(false);
        jTextField14.setVisible(false);
        jTextField15.setVisible(false);
        jTextField16.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);        
        jLabel7.setVisible(false);       
        jLabel8.setVisible(false);        
        jLabel9.setVisible(false);      
        jLabel10.setVisible(false);        
        jLabel11.setVisible(false);
        jTextField12.setVisible(false);
        jTextField13.setVisible(false);
        jTextField14.setVisible(false);
        jTextField15.setVisible(false);
        jTextField16.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);        
        jLabel7.setVisible(false);        
        jLabel8.setVisible(false);        
        jLabel9.setVisible(false);       
        jLabel10.setVisible(false);        
        jLabel11.setVisible(false);
        submit.setVisible(false);
        clear.setVisible(false);
        overall_rating.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        continue_togive_fb = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        rating = new javax.swing.JTextField();
        performance = new javax.swing.JTextField();
        overall_rating = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("WELCOME TO CANTEEN FEEDBACK FORM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 410, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Enter your E-mail id");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 170, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Enter your User-ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 67, 130, 20));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 130, 30));

        continue_togive_fb.setBackground(new java.awt.Color(51, 255, 0));
        continue_togive_fb.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        continue_togive_fb.setText("Continue to give feedback");
        continue_togive_fb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continue_togive_fbActionPerformed(evt);
            }
        });
        getContentPane().add(continue_togive_fb, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, 200, 30));

        jTextField6.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 0, 0));
        jTextField6.setText("DIRECTIONS :");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        jTextField7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(204, 0, 0));
        jTextField7.setText("For each item please indicate your level of agreement with the following statement by choosing a score between 1 and 5.");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 760, -1));

        jTextField8.setFont(new java.awt.Font("Times New Roman", 3, 15)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(255, 0, 0));
        jTextField8.setText("1. POOR");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jTextField9.setFont(new java.awt.Font("Times New Roman", 3, 15)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(255, 0, 0));
        jTextField9.setText("2. FAIR");
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        jTextField10.setFont(new java.awt.Font("Times New Roman", 3, 15)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(255, 0, 0));
        jTextField10.setText("3. GOOD");
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, -1, -1));

        jTextField11.setFont(new java.awt.Font("Times New Roman", 3, 15)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(255, 0, 0));
        jTextField11.setText("4. VERY GOOD");
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, -1, -1));

        jTextField12.setFont(new java.awt.Font("Times New Roman", 3, 15)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(255, 0, 0));
        jTextField12.setText("5. EXCELLENT");
        getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, -1, -1));

        jTextField3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(204, 0, 51));
        jTextField3.setText("Heigher score indicates a stronger agreement with the statement.");
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feedback/feedback.jepg.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 380, 270));

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 15)); // NOI18N
        jLabel5.setText("1)    Taste / Flavour ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 180, -1));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 15)); // NOI18N
        jLabel6.setText("2)    Value of money");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 160, -1));

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 15)); // NOI18N
        jLabel7.setText("3)     Food Freshness");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 200, -1));

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 15)); // NOI18N
        jLabel8.setText("4)        Portion size");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 150, -1));

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 15)); // NOI18N
        jLabel9.setText("5)         Canteen Hygiene");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, 220, -1));

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 15)); // NOI18N
        jLabel10.setText("6)          Food menu choice");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 490, 220, -1));

        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 1, 15)); // NOI18N
        jLabel11.setText("RESULT");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 640, 70, -1));

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 70, 40));

        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 70, 40));

        jTextField13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField13KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, 70, 40));

        jTextField14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField14KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 350, 80, 40));

        jTextField15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField15KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 420, 80, 40));

        jTextField16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField16KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 490, 80, 40));
        getContentPane().add(rating, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 580, 160, 30));
        getContentPane().add(performance, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 630, 160, 30));

        overall_rating.setBackground(new java.awt.Color(51, 204, 0));
        overall_rating.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        overall_rating.setText("OVERALL   RATING");
        overall_rating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overall_ratingActionPerformed(evt);
            }
        });
        getContentPane().add(overall_rating, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 580, 190, -1));

        submit.setBackground(new java.awt.Color(51, 204, 0));
        submit.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 620, -1, -1));

        clear.setBackground(new java.awt.Color(51, 204, 0));
        clear.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 620, -1, -1));

        back.setBackground(new java.awt.Color(51, 204, 0));
        back.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 620, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feedback/LGT CLRS.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void continue_togive_fbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continue_togive_fbActionPerformed
        // TODO add your handling code here:
         if(jTextField1.getText().isEmpty()||jTextField2.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"ENTER VALUES FOR ALL FIELDS");
        }
        else
        {
            String url="jdbc:derby://localhost:1527/student";
                    String user="vaishnavi";
                    String pass="vaishu";
                    String emailid,userid;
                    emailid=jTextField1.getText();
                    userid=jTextField2.getText();
                    try
                    {
                        PreparedStatement pst;
                        ResultSet rs;
                        Connection con=(Connection)DriverManager.getConnection(url,user,pass);
                        String query="select email,id from register where email=? and id=?";
                        pst=con.prepareStatement(query);
                        pst.setString(1,emailid);
                        pst.setString(2,userid);
                        rs=pst.executeQuery();
                        if(rs.next())
                        {
                          JOptionPane.showMessageDialog(null,"YOU CAN GIVE FEEDBACK");
                          rating.setVisible(true);
                          performance.setVisible(true);
                          jTextField6.setVisible(true);
                          jTextField7.setVisible(true);
                          jTextField3.setVisible(true);       
                          jTextField4.setVisible(true);        
                          jTextField5.setVisible(true);
                          jTextField8.setVisible(true);
                          jTextField9.setVisible(true);
                          jTextField10.setVisible(true);        
                          jTextField11.setVisible(true);
                          jTextField12.setVisible(true);
                          jTextField13.setVisible(true);
                          jTextField14.setVisible(true);
                          jTextField15.setVisible(true);
                          jTextField16.setVisible(true);
                          jLabel5.setVisible(true);
                          jLabel6.setVisible(true);        
                          jLabel7.setVisible(true);        
                          jLabel8.setVisible(true);        
                          jLabel9.setVisible(true);       
                          jLabel10.setVisible(true);        
                          jLabel11.setVisible(true);
                          submit.setVisible(true);
                          clear.setVisible(true);
                          overall_rating.setVisible(true);
                         
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null,"Please input val Email-ID and User-ID");
                        }
                    }
                    catch(Exception e)
                    {
                       JOptionPane.showMessageDialog(null,e.toString()); 
                    }
        
        }
    }//GEN-LAST:event_continue_togive_fbActionPerformed

    private void overall_ratingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overall_ratingActionPerformed
        // TODO add your handling code here:
        if(jTextField4.getText().isEmpty()||jTextField5.getText().isEmpty()||jTextField13.getText().isEmpty()||jTextField14.getText().isEmpty()||jTextField15.getText().isEmpty()||jTextField16.getText().isEmpty())
        {
          JOptionPane.showMessageDialog(null,"ENTER VALUES FOR ALL FIELDS");  
        }
        else
        {
            int a,b,c,d,e,f,result;
            a=Integer.parseInt(jTextField4.getText());
            b=Integer.parseInt(jTextField5.getText());
            c=Integer.parseInt(jTextField13.getText());
            d=Integer.parseInt(jTextField14.getText());
            e=Integer.parseInt(jTextField15.getText());
            f=Integer.parseInt(jTextField16.getText());
            result=a+b+c+d+e+f;
            rating.setText(""+result);
            if(result<=6)
               performance.setText("POOR");
            else if(result>6&&result<=12)
               performance.setText("FAIR");
            else if(result>12&&result<=18)
               performance.setText("GOOD"); 
            else if(result>18&&result<=24)
               performance.setText("VERY GOOD");
            else if(result>24&&result<=30)
                performance.setText("EXCELLENT");
            else if(result>30)
                performance.setText("WRONG INPUT");   
        }
    }//GEN-LAST:event_overall_ratingActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
         if(jTextField4.getText().isEmpty()||jTextField5.getText().isEmpty()||jTextField13.getText().isEmpty()||jTextField14.getText().isEmpty()||jTextField15.getText().isEmpty()||jTextField16.getText().isEmpty())
        {
          JOptionPane.showMessageDialog(null,"ENTER VALUES FOR ALL FIELDS");  
        }
        else
         {
          try
            {
              String url="jdbc:derby://localhost:1527/student";
                String user="vaishnavi";
                String pass="vaishu";
                Connection con=(Connection)DriverManager.getConnection(url,user,pass);
                Statement stmt=(Statement)con.createStatement();
                String query="insert into canteenresult(mail,rating,result)values('"+jTextField1.getText()+"','"+rating.getText()+"','"+performance.getText()+"')";
                stmt.execute(query);
                JOptionPane.showMessageDialog(null,"FEEDBACK ACCEPTED");  
            }
          catch(Exception e)
            {
             JOptionPane.showMessageDialog(null,e.toString());       
            }
         }
    }//GEN-LAST:event_submitActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField13.setText("");
        jTextField14.setText("");
        jTextField15.setText("");
        jTextField16.setText("");
        rating.setText("");
        performance.setText("");
        
    }//GEN-LAST:event_clearActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new student_choosetypes().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        // TODO add your handling code here:
        String ph=jTextField4.getText();
        int length= ph.length();
        char c=evt.getKeyChar();
        if(evt.getKeyChar()>='1'&&evt.getKeyChar()<='5'&&ph.length()<1||c==KeyEvent.VK_BACK_SPACE)
        {
            jTextField4.setEditable(true);
        }
        else
        {
             jTextField4.setEditable(false);
        }
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        // TODO add your handling code here:
        String ph=jTextField13.getText();
        int length= ph.length();
        char c=evt.getKeyChar();
        if(evt.getKeyChar()>='1'&&evt.getKeyChar()<='5'&&ph.length()<1||c==KeyEvent.VK_BACK_SPACE)
        {
            jTextField5.setEditable(true);
        }
        else
        {
             jTextField5.setEditable(false);
        }
    }//GEN-LAST:event_jTextField5KeyTyped

    private void jTextField13KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField13KeyTyped
        // TODO add your handling code here:
        String ph=jTextField13.getText();
        int length= ph.length();
        char c=evt.getKeyChar();
        if(evt.getKeyChar()>='1'&&evt.getKeyChar()<='5'&&ph.length()<1||c==KeyEvent.VK_BACK_SPACE)
        {
            jTextField13.setEditable(true);
        }
        else
        {
             jTextField13.setEditable(false);
        }
    }//GEN-LAST:event_jTextField13KeyTyped

    private void jTextField14KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField14KeyTyped
        // TODO add your handling code here:
        String ph=jTextField14.getText();
        int length= ph.length();
        char c=evt.getKeyChar();
        if(evt.getKeyChar()>='1'&&evt.getKeyChar()<='5'&&ph.length()<1||c==KeyEvent.VK_BACK_SPACE)
        {
            jTextField14.setEditable(true);
        }
        else
        {
             jTextField14.setEditable(false);
        }
    }//GEN-LAST:event_jTextField14KeyTyped

    private void jTextField15KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField15KeyTyped
        // TODO add your handling code here:
        String ph=jTextField15.getText();
        int length= ph.length();
        char c=evt.getKeyChar();
        if(evt.getKeyChar()>='1'&&evt.getKeyChar()<='5'&&ph.length()<1||c==KeyEvent.VK_BACK_SPACE)
        {
            jTextField15.setEditable(true);
        }
        else
        {
             jTextField15.setEditable(false);
        }
    }//GEN-LAST:event_jTextField15KeyTyped

    private void jTextField16KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField16KeyTyped
        // TODO add your handling code here:
        String ph=jTextField16.getText();
        int length= ph.length();
        char c=evt.getKeyChar();
        if(evt.getKeyChar()>='1'&&evt.getKeyChar()<='5'&&ph.length()<1||c==KeyEvent.VK_BACK_SPACE)
        {
            jTextField16.setEditable(true);
        }
        else
        {
             jTextField16.setEditable(false);
        }
    }//GEN-LAST:event_jTextField16KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(canteen_feedbackform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(canteen_feedbackform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(canteen_feedbackform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(canteen_feedbackform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new canteen_feedbackform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton clear;
    private javax.swing.JButton continue_togive_fb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton overall_rating;
    private javax.swing.JTextField performance;
    private javax.swing.JTextField rating;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
