/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feedback;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
/**
 *
 * @author Lenovo
 */
public class event_feedbackform extends javax.swing.JFrame {

    /**
     * Creates new form event_feedbackform
     */
    public event_feedbackform() {
        initComponents();
        jComboBox1.setVisible(false);
        pgm_name.setVisible(false);
        jTextField6.setVisible(false);
        jTextField7.setVisible(false);
        jTextField8.setVisible(false);
        jTextField9.setVisible(false);
        jTextField10.setVisible(false);
        jTextField11.setVisible(false);
        jTextField12.setVisible(false);
        jTextField4.setVisible(false);
        jTextField5.setVisible(false);
        jTextField13.setVisible(false);
        jTextField14.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        overallrating.setVisible(false);
        submit.setVisible(false);
        clear.setVisible(false);
        overall_rating.setVisible(false);
        performance.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        continue_feedback = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        pgm_name = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        overall_rating = new javax.swing.JTextField();
        performance = new javax.swing.JTextField();
        overallrating = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("WELCOME TO EVENT FEEDBACK FORM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 410, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Enter your E-mail id");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 170, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Enter your user-id");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 150, 30));

        continue_feedback.setBackground(new java.awt.Color(255, 255, 0));
        continue_feedback.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        continue_feedback.setText("Continue to give feedback");
        continue_feedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continue_feedbackActionPerformed(evt);
            }
        });
        jPanel1.add(continue_feedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, 270, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("PROGRAMM NAME: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT PROGRAMM", "Welcome Day", "Orientation Day", "Traditional Day", "Ethnic Day", "Farewell Party", "Talent Show", "Sports Day" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 180, 30));
        jPanel1.add(pgm_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 170, 30));

        jTextField6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(153, 0, 0));
        jTextField6.setText("DIRECTIONS :");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jTextField7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 0, 51));
        jTextField7.setText("For each item please indicate your level of agreement with the following statement by choosing a score between 1 and 5.");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 770, -1));

        jTextField8.setFont(new java.awt.Font("Times New Roman", 3, 15)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(204, 0, 0));
        jTextField8.setText("1. POOR");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jTextField9.setFont(new java.awt.Font("Times New Roman", 3, 15)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(204, 0, 0));
        jTextField9.setText("2. FAIR");
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        jTextField10.setFont(new java.awt.Font("Times New Roman", 3, 15)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(204, 0, 0));
        jTextField10.setText("3. GOOD");
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));

        jTextField11.setFont(new java.awt.Font("Times New Roman", 3, 15)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(204, 0, 0));
        jTextField11.setText("4. VERY GOOD");
        jPanel1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, -1, -1));

        jTextField12.setFont(new java.awt.Font("Times New Roman", 3, 15)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(204, 0, 0));
        jTextField12.setText("5. EXCELLENT");
        jPanel1.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 15)); // NOI18N
        jLabel5.setText("1]       Time management");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 15)); // NOI18N
        jLabel6.setText("2]       Venue arrangement");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 15)); // NOI18N
        jLabel7.setText("3]        Hospitality");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 15)); // NOI18N
        jLabel8.setText("4]        Lunch management");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        jLabel9.setText("RESULT");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 630, 70, -1));

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 60, 40));

        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, 60, 40));

        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jTextField13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField13KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 350, 70, 40));

        jTextField14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField14KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, 70, 40));
        jPanel1.add(overall_rating, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, 180, 30));
        jPanel1.add(performance, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 630, 180, 30));

        overallrating.setBackground(new java.awt.Color(255, 255, 51));
        overallrating.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        overallrating.setText("OVERALL RATING");
        overallrating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overallratingActionPerformed(evt);
            }
        });
        jPanel1.add(overallrating, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 560, 190, 40));

        submit.setBackground(new java.awt.Color(255, 255, 51));
        submit.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 600, 130, 40));

        clear.setBackground(new java.awt.Color(255, 255, 51));
        clear.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 600, 130, 40));

        back.setBackground(new java.awt.Color(255, 255, 51));
        back.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 600, 130, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feedback/your-voice-matters-image.png"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 140, 290, 240));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feedback/LGT CLRS.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 680));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void overallratingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overallratingActionPerformed
        // TODO add your handling code here:
        if(pgm_name.getText().isEmpty()||jTextField4.getText().isEmpty()||jTextField4.getText().isEmpty()||jTextField5.getText().isEmpty()||jTextField13.getText().isEmpty()||jTextField14.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"ENTER VALUES FOR ALL FIELDS");
        }  
        else
        {
            int a,b,c,d,result;
            a=Integer.parseInt(jTextField4.getText());
            b=Integer.parseInt(jTextField5.getText());
            c=Integer.parseInt(jTextField13.getText());
            d=Integer.parseInt(jTextField14.getText());
            result=a+b+c+d;
            overall_rating.setText(""+result);    //rating textfield
            if(result<=4)
                performance.setText("POOR");   //result textfield
            else if(result>4&&result<=8)
                performance.setText("FAIR");
            else if(result>8&&result<=12)
                performance.setText("GOOD");
            else if(result>12&&result<=16)
                performance.setText("VERY GOOD");
            else if(result>16&&result<=20)    
                performance.setText("EXCELLENT");
            else if(result>20)
                performance.setText("WRONG INPUT");    
        }
    }//GEN-LAST:event_overallratingActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        if(pgm_name.getText().isEmpty()||jTextField4.getText().isEmpty()||jTextField4.getText().isEmpty()||jTextField5.getText().isEmpty()||jTextField13.getText().isEmpty()||jTextField14.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"ENTER VALUES FOR ALL FIELDS");
        }  
        else
        {
            try
            {
                String url="jdbc:derby://localhost:1527/student";
                String user="vaishnavi";
                String pass="vaishu";
                Connection con=(Connection)DriverManager.getConnection(url,user,pass);
                Statement stmt=(Statement)con.createStatement();
                String query="insert into eventresult(eventname,mail,uid,result, rating)values('"+pgm_name.getText()+"','"+jTextField1.getText()+"','"+jTextField2.getText()+"','"+performance.getText()+"','"+overall_rating.getText()+"')";
                stmt.execute(query);
                JOptionPane.showMessageDialog(null,"FEEDBACK ACCEPTED");
            }
            catch(Exception e)
            {
              JOptionPane.showMessageDialog(null,e.toString());  
            }
        }
        
    }//GEN-LAST:event_submitActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        jComboBox1.setSelectedItem("SELECT AN EVENT");
        pgm_name.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField13.setText("");
        jTextField14.setText("");
        overall_rating.setText("");
        performance.setText("");  
    }//GEN-LAST:event_clearActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new student_choosetypes().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void continue_feedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continue_feedbackActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().isEmpty()||jTextField2.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"ENTER VALUES FOR ALL FIELDS");
        }
        else
        {
            String url="jdbc:derby://localhost:1527/student";
                    String user="vaishnavi";
                    String pass="vaishu";
                    String emailid,userid;
                    emailid=jTextField1.getText();
                    userid=jTextField2.getText();
                    try
                    {
                        PreparedStatement pst;
                        ResultSet rs=null;
                        Connection con=(Connection)DriverManager.getConnection(url,user,pass);
                        String query="select email,id from register where email=? and id=?";
                        pst=con.prepareStatement(query);
                        pst.setString(1,emailid);
                        pst.setString(2,userid);
                        rs=pst.executeQuery();
                        if(rs.next())
                        {
                          JOptionPane.showMessageDialog(null,"YOU CAN GIVE FEEDBACK");
                          jComboBox1.setVisible(true);
                           pgm_name.setVisible(true);
                           jTextField6.setVisible(true);
                           jTextField7.setVisible(true);
                           jTextField8.setVisible(true);
                           jTextField9.setVisible(true);
                           jTextField10.setVisible(true);
                           jTextField11.setVisible(true);
                           jTextField12.setVisible(true);
                           jTextField4.setVisible(true);
                           jTextField5.setVisible(true);
                           jTextField13.setVisible(true);
                           jTextField14.setVisible(true);
                           jLabel4.setVisible(true);
                           jLabel5.setVisible(true);
                           jLabel6.setVisible(true);
                           jLabel7.setVisible(true);
                           jLabel8.setVisible(true);
                           jLabel9.setVisible(true);
                           overallrating.setVisible(true);
                           submit.setVisible(true);
                           clear.setVisible(true);
                           overall_rating.setVisible(true);
                           performance.setVisible(true); 
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null,"Please input val Email-ID and User-ID");
                        }
                    }
                    catch(Exception e)
                    {
                       JOptionPane.showMessageDialog(null,e.toString()); 
                    }
        }
    }//GEN-LAST:event_continue_feedbackActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here
        String value=(String)jComboBox1.getSelectedItem();
        pgm_name.setText(value);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        // TODO add your handling code here:
        String ph=jTextField4.getText();
        int length= ph.length();
        char c=evt.getKeyChar();
        if(evt.getKeyChar()>='1'&&evt.getKeyChar()<='5'&&ph.length()<1||c==KeyEvent.VK_BACK_SPACE)
        {
            jTextField4.setEditable(true);
        }
        else
        {
             jTextField4.setEditable(false);
        }
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        // TODO add your handling code here:
        String ph=jTextField5.getText();
        int length= ph.length();
        char c=evt.getKeyChar();
        if(evt.getKeyChar()>='1'&&evt.getKeyChar()<='5'&&ph.length()<1||c==KeyEvent.VK_BACK_SPACE)
        {
            jTextField5.setEditable(true);
        }
        else
        {
             jTextField5.setEditable(false);
        }
    }//GEN-LAST:event_jTextField5KeyTyped

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField13KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField13KeyTyped
        // TODO add your handling code here:
        String ph=jTextField13.getText();
        int length= ph.length();
        char c=evt.getKeyChar();
        if(evt.getKeyChar()>='1'&&evt.getKeyChar()<='5'&&ph.length()<1||c==KeyEvent.VK_BACK_SPACE)
        {
            jTextField13.setEditable(true);
        }
        else
        {
             jTextField13.setEditable(false);
        }
    }//GEN-LAST:event_jTextField13KeyTyped

    private void jTextField14KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField14KeyTyped
        // TODO add your handling code here:
        String ph=jTextField14.getText();
        int length= ph.length();
        char c=evt.getKeyChar();
        if(evt.getKeyChar()>='1'&&evt.getKeyChar()<='5'&&ph.length()<1||c==KeyEvent.VK_BACK_SPACE)
        {
            jTextField14.setEditable(true);
        }
        else
        {
             jTextField14.setEditable(false);
        }
    }//GEN-LAST:event_jTextField14KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(event_feedbackform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(event_feedbackform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(event_feedbackform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(event_feedbackform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new event_feedbackform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton clear;
    private javax.swing.JButton continue_feedback;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField overall_rating;
    private javax.swing.JButton overallrating;
    private javax.swing.JTextField performance;
    private javax.swing.JTextField pgm_name;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
