/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feedback;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.Statement;
/**
 *
 * @author Lenovo
 */
public class faculty_feedbackform extends javax.swing.JFrame {

    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    /**
     * Creates new form faculty_feedbackform
     */
    public faculty_feedbackform() {
        initComponents();
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel15.setVisible(false);
        jLabel16.setVisible(false);
        jLabel17.setVisible(false);
        jLabel18.setVisible(false);
        jLabel19.setVisible(false);
        jLabel20.setVisible(false);
        jLabel21.setVisible(false);
        jLabel22.setVisible(false);
        jLabel23.setVisible(false);
        jLabel24.setVisible(false);
        jLabel25.setVisible(false);
        jLabel26.setVisible(false);
        jLabel27.setVisible(false);
        jComboBox1.setVisible(false);
        fname.setVisible(false);
        dept.setVisible(false);
        branch.setVisible(false);
        jTextField6.setVisible(false);
        jTextField7.setVisible(false);
        jTextField8.setVisible(false);
        jTextField9.setVisible(false);
        jTextField10.setVisible(false);
        jTextField11.setVisible(false);
        jTextField12.setVisible(false);
        jTextField13.setVisible(false);
        jTextField14.setVisible(false);
        jTextField15.setVisible(false);
        jTextField16.setVisible(false);
        jTextField17.setVisible(false);
        jTextField18.setVisible(false);
        jTextField19.setVisible(false); 
        jTextField20.setVisible(false);
        jTextField21.setVisible(false);
        jTextField22.setVisible(false);
        jTextField23.setVisible(false);
        jTextField24.setVisible(false);
        jTextField25.setVisible(false);
        jTextField26.setVisible(false);
        jTextField27.setVisible(false);
        overallrating.setVisible(false);
        performance.setVisible(false);
        over_all_rating.setVisible(false);
        submit.setVisible(false);        
        clear.setVisible(false);       
        combobox();            
    }

    
    
    public void combobox()
    {
        try
        {
            con=DriverManager.getConnection("jdbc:derby://localhost:1527/student","vaishnavi","vaishu");
            String sql="select * from staff";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next())
            {
                String fname=rs.getString("fname");
                jComboBox1.addItem(fname);
       
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.toString());
            }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        dept = new javax.swing.JTextField();
        branch = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        over_all_rating = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        overallrating = new javax.swing.JTextField();
        performance = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        continue_to_give_feedback = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("WELCOME TO FACULTY FEEDBACK FORM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 410, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Enter your E-mail id");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Enter your user-id");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("FACULTY NAME");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("DEPARTMENT");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("BRANCH");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 120, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 170, 30));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 170, 30));
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 170, 30));
        getContentPane().add(dept, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, 170, 30));
        getContentPane().add(branch, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 110, 140, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT FACULTY" }));
        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 160, 30));

        jTextField6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 0, 0));
        jTextField6.setText("DIRECTIONS :");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        jTextField7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 0, 51));
        jTextField7.setText("For each item please indicate your level of agreement with the following statement by choosing a score between 1 and 5.");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 770, -1));

        jTextField8.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(255, 0, 0));
        jTextField8.setText("1. POOR");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        jTextField9.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(255, 0, 0));
        jTextField9.setText("2. FAIR");
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, -1));

        jTextField10.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(255, 0, 0));
        jTextField10.setText("3. GOOD");
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, -1, -1));

        jTextField11.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(255, 0, 0));
        jTextField11.setText("4. VERY GOOD");
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, -1, -1));

        jTextField12.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(255, 0, 0));
        jTextField12.setText("5. EXCELLENT");
        getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        jLabel7.setText("Does the faculty comes on time ?");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 230, -1));

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        jLabel8.setText("Faculty is well prepared.");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 160, -1));

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        jLabel9.setText("Are aims and objectives made clear.");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 240, -1));

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        jLabel10.setText("Subject matter organized in a logical");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 240, -1));

        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        jLabel11.setText("manner ?");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 80, -1));

        jLabel12.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        jLabel12.setText("Faculty is well planned ?");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 160, -1));

        jTextField13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField13KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 60, 30));

        jTextField14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField14KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 60, 30));

        jTextField15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField15KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 60, 40));

        jTextField16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField16KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 60, 40));

        jTextField17.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField17KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 60, 40));

        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        jLabel13.setText("Faculty speaks clearly and audibly ?");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 240, -1));

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        jLabel14.setText("Faculty provides real time examples ?");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 260, -1));

        jLabel15.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        jLabel15.setText("Faculty comes well prepared.");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 210, -1));

        jLabel16.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        jLabel16.setText("Faculty provides ability to bring");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, 230, -1));

        jLabel17.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        jLabel17.setText("conceptual clarity & promotion");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, 220, -1));

        jLabel18.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        jLabel18.setText("of thinking ability");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 540, 150, -1));

        jTextField18.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField18KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 60, 40));

        jTextField19.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField19KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 60, 40));

        jTextField20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField20KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, 60, 40));

        jTextField21.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField21KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 490, 60, 40));

        jLabel19.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        jLabel19.setText("Faculty writes / draws clearly.");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 280, 200, -1));

        jLabel20.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        jLabel20.setText("Faculty offers assistance &");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 350, 180, -1));

        jLabel21.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        jLabel21.setText("councelling.");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 380, 90, -1));

        jLabel22.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        jLabel22.setText("Faculty encourages creativity.");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 460, 200, -1));
        getContentPane().add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 280, 70, 40));
        getContentPane().add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 360, 70, 40));
        getContentPane().add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 460, 70, 40));

        jLabel23.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        jLabel23.setText("Faculty encourages raising doubts.");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 290, 230, -1));

        jLabel24.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        jLabel24.setText("Faculty pace is good. not very fast.");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 370, 240, -1));

        jLabel25.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        jLabel25.setText("Faculty asks relevant questions for");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 460, 240, -1));

        jLabel26.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        jLabel26.setText("interaction.");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 490, 90, -1));
        getContentPane().add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 290, 60, 40));
        getContentPane().add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 370, 60, 40));
        getContentPane().add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 460, 60, 40));

        over_all_rating.setBackground(new java.awt.Color(255, 255, 51));
        over_all_rating.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        over_all_rating.setText("OVERALL RATING");
        over_all_rating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                over_all_ratingActionPerformed(evt);
            }
        });
        getContentPane().add(over_all_rating, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 590, 190, 40));

        submit.setBackground(new java.awt.Color(255, 255, 51));
        submit.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 590, 160, 40));

        clear.setBackground(new java.awt.Color(255, 255, 51));
        clear.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 590, 160, 40));

        back.setBackground(new java.awt.Color(255, 255, 51));
        back.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 590, 160, 40));

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel27.setText("RESULT");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 650, 80, -1));
        getContentPane().add(overallrating, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 590, 200, 30));
        getContentPane().add(performance, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 650, 200, 30));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feedback/ooooooooooooooooooooo.jpg"))); // NOI18N
        jLabel28.setText("jLabel28");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 0, 260, 200));

        continue_to_give_feedback.setBackground(new java.awt.Color(255, 255, 0));
        continue_to_give_feedback.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        continue_to_give_feedback.setText("Continue to give feedback");
        continue_to_give_feedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continue_to_give_feedbackActionPerformed(evt);
            }
        });
        getContentPane().add(continue_to_give_feedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 60, 270, 30));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feedback/LGT CLRS.jpg"))); // NOI18N
        jLabel29.setText("jLabel29");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void continue_to_give_feedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continue_to_give_feedbackActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().isEmpty()||jTextField2.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"ENTER VALUES FOR ALL FIELDS");
        }
        else
        {
             String url="jdbc:derby://localhost:1527/student";
                    String user="vaishnavi";
                    String pass="vaishu";
                    String emailid,userid;
                    emailid=jTextField1.getText();
                    userid=jTextField2.getText();
                    try
                    {
                        PreparedStatement pst;
                        ResultSet rs=null;
                        Connection con=(Connection)DriverManager.getConnection(url,user,pass);
                        String query="select email,id from register where email=? and id=?";
                        pst=con.prepareStatement(query);
                        pst.setString(1,emailid);
                        pst.setString(2,userid);
                        rs=pst.executeQuery();
                        if(rs.next())
                        {
                          JOptionPane.showMessageDialog(null,"YOU CAN GIVE FEEDBACK");
                          jLabel4.setVisible(true);
                          jLabel5.setVisible(true);
                          jLabel6.setVisible(true);;
                          jLabel7.setVisible(true);
                          jLabel8.setVisible(true);
                          jLabel9.setVisible(true);
                          jLabel10.setVisible(true);
                          jLabel11.setVisible(true);
                          jLabel12.setVisible(true);
                          jLabel13.setVisible(true);
                          jLabel14.setVisible(true);
                          jLabel15.setVisible(true);
                          jLabel16.setVisible(true);
                          jLabel17.setVisible(true);
                          jLabel18.setVisible(true);
                          jLabel19.setVisible(true);
                          jLabel20.setVisible(true);
                          jLabel21.setVisible(true);
                          jLabel22.setVisible(true);
                          jLabel23.setVisible(true);
                          jLabel24.setVisible(true);
                          jLabel25.setVisible(true);
                          jLabel26.setVisible(true);
                          jLabel27.setVisible(true);
                          jComboBox1.setVisible(true);
                          fname.setVisible(true);
                          dept.setVisible(true);
                          branch.setVisible(true);
                          jTextField6.setVisible(true);
                          jTextField7.setVisible(true);
                          jTextField8.setVisible(true);
                          jTextField9.setVisible(true);
                          jTextField10.setVisible(true);
                          jTextField11.setVisible(true);
                          jTextField12.setVisible(true);
                          jTextField13.setVisible(true);
                          jTextField14.setVisible(true);
                          jTextField15.setVisible(true);
                          jTextField16.setVisible(true);
                          jTextField17.setVisible(true);
                          jTextField18.setVisible(true);
                          jTextField19.setVisible(true);
                          jTextField20.setVisible(true);
                          jTextField21.setVisible(true);
                          jTextField22.setVisible(true);
                          jTextField23.setVisible(true);
                          jTextField24.setVisible(true);
                          jTextField25.setVisible(true);
                          jTextField26.setVisible(true);
                          jTextField27.setVisible(true);
                          overallrating.setVisible(true);
                          performance.setVisible(true);
                          over_all_rating.setVisible(true);
                          submit.setVisible(true);     
                          clear.setVisible(true);        
                           
                          
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null,"Please input val Email-ID and User-ID");
                        }
                    }
                    catch(Exception e)
                    {
                       JOptionPane.showMessageDialog(null,e.toString()); 
                    }
        }
    }//GEN-LAST:event_continue_to_give_feedbackActionPerformed

    private void over_all_ratingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_over_all_ratingActionPerformed
        // TODO add your handling code here:
        if(fname.getText().isEmpty()||dept.getText().isEmpty()||branch.getText().isEmpty()||jTextField13.getText().isEmpty()||jTextField14.getText().isEmpty()||jTextField15.getText().isEmpty()||jTextField16.getText().isEmpty()||jTextField17.getText().isEmpty()||jTextField18.getText().isEmpty()||jTextField19.getText().isEmpty()||jTextField20.getText().isEmpty()||jTextField21.getText().isEmpty()||jTextField22.getText().isEmpty()||jTextField23.getText().isEmpty()||jTextField24.getText().isEmpty()||jTextField25.getText().isEmpty()||jTextField26.getText().isEmpty()||jTextField27.getText().isEmpty())
        {
          JOptionPane.showMessageDialog(null,"ENTER VALUES FOR ALL FIELDS");  
        } 
        else
        {
            int a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,result;
            a=Integer.parseInt(jTextField13.getText());
            b=Integer.parseInt(jTextField14.getText());
            c=Integer.parseInt(jTextField15.getText());
            d=Integer.parseInt(jTextField16.getText());
            e=Integer.parseInt(jTextField17.getText());
            f=Integer.parseInt(jTextField18.getText());
            g=Integer.parseInt(jTextField19.getText());
            h=Integer.parseInt(jTextField20.getText());
            i=Integer.parseInt(jTextField21.getText());
            j=Integer.parseInt(jTextField22.getText());
            k=Integer.parseInt(jTextField23.getText());
            l=Integer.parseInt(jTextField24.getText());
            m=Integer.parseInt(jTextField25.getText());
            n=Integer.parseInt(jTextField26.getText());
            o=Integer.parseInt(jTextField27.getText());
            result=a+b+c+d+e+f+g+h+i+j+k+l+m+n+o;
            overallrating.setText(""+result);
            if(result<=15)
                performance.setText("POOR");
               else if(result>15&&result<=30)
                 performance.setText("FAIR");
               else if(result>30&&result<=45)
                 performance.setText("GOOD");  
               else if(result>45&&result<=60)
                 performance.setText("VERY GOOD");  
               else if(result>60&&result<=75)
                 performance.setText("EXCELLENT");
               else if(result>75)
                  performance.setText("WRONG INPUT");    
        }
            
    }//GEN-LAST:event_over_all_ratingActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        if(fname.getText().isEmpty()||dept.getText().isEmpty()||branch.getText().isEmpty()||jTextField13.getText().isEmpty()||jTextField14.getText().isEmpty()||jTextField15.getText().isEmpty()||jTextField16.getText().isEmpty()||jTextField17.getText().isEmpty()||jTextField18.getText().isEmpty()||jTextField19.getText().isEmpty()||jTextField20.getText().isEmpty()||jTextField21.getText().isEmpty()||jTextField22.getText().isEmpty()||jTextField23.getText().isEmpty()||jTextField24.getText().isEmpty()||jTextField25.getText().isEmpty()||jTextField26.getText().isEmpty()||jTextField27.getText().isEmpty())
        {
          JOptionPane.showMessageDialog(null,"ENTER VALUES FOR ALL FIELDS");  
        } 
        else
        {
            try
            {
                String url="jdbc:derby://localhost:1527/student";
                String user="vaishnavi";
                String pass="vaishu";
                Connection con=(Connection)DriverManager.getConnection(url,user,pass);
                Statement stmt=(Statement)con.createStatement();
                String query="insert into factable(name,department,branch,result,rating)values('"+fname.getText()+"','"+dept.getText()+"','"+branch.getText()+"','"+performance.getText()+"','"+overallrating.getText()+"')";
                stmt.execute(query);
                JOptionPane.showMessageDialog(null,"FEEDBACK ACCEPTED");
            }
            catch(Exception e)
            {
            JOptionPane.showMessageDialog(null,e.toString());    
            }
        }
        
    }//GEN-LAST:event_submitActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        jComboBox1.setSelectedItem("SELECT  ID");
        fname.setText("");
        dept.setText("");
        branch.setText("");
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField13.setText("");
        jTextField14.setText("");
        jTextField15.setText("");
        jTextField16.setText("");
        jTextField17.setText("");
        jTextField18.setText("");
        jTextField19.setText("");
        jTextField20.setText("");
        jTextField21.setText("");
        jTextField22.setText("");
        jTextField23.setText("");
        jTextField24.setText("");
        jTextField25.setText("");
        jTextField26.setText("");
        jTextField27.setText("");
        overallrating.setText("");
        performance.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new student_choosetypes().setVisible(true);
        
    }//GEN-LAST:event_backActionPerformed

    private void jComboBox1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeInvisible
        // First impoer values to combobox
        //selecting combobox values to text field
        String tmp=(String)jComboBox1.getSelectedItem();
        String sql="select * from staff where fname=?";
        try
        {
          pst=con.prepareStatement(sql);
          pst.setString(1,tmp);
          rs=pst.executeQuery();
          while(rs.next())
          {
              String add1=rs.getString("fname");
              fname.setText(add1);
              String add2=rs.getString("dept");
              dept.setText(add2);
              String add3=rs.getString("branch");
              branch.setText(add3); 
          }
        }
          catch(Exception e)
                  {
                  JOptionPane.showMessageDialog(null,e.toString());    
                  }
        
    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeInvisible

    private void jTextField13KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField13KeyTyped
        // TODO add your handling code here:
        String ph=jTextField13.getText();
        int length= ph.length();
        char c=evt.getKeyChar();
        if(evt.getKeyChar()>='1'&&evt.getKeyChar()<='5'&&ph.length()<1||c==KeyEvent.VK_BACK_SPACE)
        {
            jTextField13.setEditable(true);
        }
        else
        {
             jTextField13.setEditable(false);
        }
       
    }//GEN-LAST:event_jTextField13KeyTyped

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField14KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField14KeyTyped
        // TODO add your handling code here:
        String ph=jTextField14.getText();
        int length= ph.length();
        char c=evt.getKeyChar();
        if(evt.getKeyChar()>='1'&&evt.getKeyChar()<='5'&&ph.length()<1||c==KeyEvent.VK_BACK_SPACE)
        {
            jTextField14.setEditable(true);
        }
        else
        {
             jTextField14.setEditable(false);
        }
    }//GEN-LAST:event_jTextField14KeyTyped

    private void jTextField15KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField15KeyTyped
    // TODO add your handling code here:
    String ph=jTextField15.getText();
        int length= ph.length();
        char c=evt.getKeyChar();
        if(evt.getKeyChar()>='1'&&evt.getKeyChar()<='5'&&ph.length()<1||c==KeyEvent.VK_BACK_SPACE)
        {
            jTextField15.setEditable(true);
        }
        else
        {
             jTextField15.setEditable(false);
        }
    }//GEN-LAST:event_jTextField15KeyTyped

    private void jTextField16KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField16KeyTyped
        // TODO add your handling code here:
        String ph=jTextField16.getText();
        int length= ph.length();
        char c=evt.getKeyChar();
        if(evt.getKeyChar()>='1'&&evt.getKeyChar()<='5'&&ph.length()<1||c==KeyEvent.VK_BACK_SPACE)
        {
            jTextField16.setEditable(true);
        }
        else
        {
             jTextField16.setEditable(false);
        }
    }//GEN-LAST:event_jTextField16KeyTyped

    private void jTextField17KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField17KeyTyped
        // TODO add your handling code here:
        String ph=jTextField17.getText();
        int length= ph.length();
        char c=evt.getKeyChar();
        if(evt.getKeyChar()>='1'&&evt.getKeyChar()<='5'&&ph.length()<1||c==KeyEvent.VK_BACK_SPACE)
        {
            jTextField17.setEditable(true);
        }
        else
        {
             jTextField17.setEditable(false);
        }
    }//GEN-LAST:event_jTextField17KeyTyped

    private void jTextField18KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField18KeyTyped
        // TODO add your handling code here:
        String ph=jTextField18.getText();
        int length= ph.length();
        char c=evt.getKeyChar();
        if(evt.getKeyChar()>='1'&&evt.getKeyChar()<='5'&&ph.length()<1||c==KeyEvent.VK_BACK_SPACE)
        {
            jTextField18.setEditable(true);
        }
        else
        {
             jTextField18.setEditable(false);
        }
    }//GEN-LAST:event_jTextField18KeyTyped

    private void jTextField19KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField19KeyTyped
        // TODO add your handling code here:
        String ph=jTextField19.getText();
        int length= ph.length();
        char c=evt.getKeyChar();
        if(evt.getKeyChar()>='1'&&evt.getKeyChar()<='5'&&ph.length()<1||c==KeyEvent.VK_BACK_SPACE)
        {
            jTextField19.setEditable(true);
        }
        else
        {
             jTextField19.setEditable(false);
        }
    }//GEN-LAST:event_jTextField19KeyTyped

    private void jTextField20KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField20KeyTyped
        // TODO add your handling code here:
        String ph=jTextField20.getText();
        int length= ph.length();
        char c=evt.getKeyChar();
        if(evt.getKeyChar()>='1'&&evt.getKeyChar()<='5'&&ph.length()<1||c==KeyEvent.VK_BACK_SPACE)
        {
            jTextField20.setEditable(true);
        }
        else
        {
             jTextField20.setEditable(false);
        }
    }//GEN-LAST:event_jTextField20KeyTyped

    private void jTextField21KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField21KeyTyped
        // TODO add your handling code here:
        String ph=jTextField21.getText();
        int length= ph.length();
        char c=evt.getKeyChar();
        if(evt.getKeyChar()>='1'&&evt.getKeyChar()<='5'&&ph.length()<1||c==KeyEvent.VK_BACK_SPACE)
        {
            jTextField21.setEditable(true);
        }
        else
        {
             jTextField21.setEditable(false);
        }
    }//GEN-LAST:event_jTextField21KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(faculty_feedbackform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(faculty_feedbackform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(faculty_feedbackform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(faculty_feedbackform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new faculty_feedbackform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField branch;
    private javax.swing.JButton clear;
    private javax.swing.JButton continue_to_give_feedback;
    private javax.swing.JTextField dept;
    private javax.swing.JTextField fname;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton over_all_rating;
    private javax.swing.JTextField overallrating;
    private javax.swing.JTextField performance;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
