/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feedback;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class library_feedbackform extends javax.swing.JFrame {

    /**
     * Creates new form library_feedbackform
     */
    public library_feedbackform() {
        initComponents();
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel15.setVisible(false);
        jLabel16.setVisible(false);
        jLabel17.setVisible(false);
        jTextField6.setVisible(false);
        jTextField7.setVisible(false);
        jTextField3.setVisible(false);
        jTextField8.setVisible(false);
        jTextField9.setVisible(false);
        jTextField10.setVisible(false);
        jTextField11.setVisible(false);
        jTextField12.setVisible(false);
        jTextField4.setVisible(false);
        jTextField5.setVisible(false);
        jTextField13.setVisible(false);
        jTextField14.setVisible(false);
        jTextField15.setVisible(false);
        jTextField16.setVisible(false);
        jTextField17.setVisible(false);
        jTextField18.setVisible(false);
        jTextField19.setVisible(false);
        jTextField20.setVisible(false);
        or.setVisible(false);
        performance.setVisible(false);
        overallrating.setVisible(false);
        submit.setVisible(false);
        clear.setVisible(false);   
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        continue_togivefb = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        overallrating = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        back = new javax.swing.JButton();
        or = new javax.swing.JTextField();
        performance = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("WELCOME TO LIBRARY FEEDBACK FORM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 470, 40));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setText("TO IMPROVE THE LIBRARY SERVICES AND THE USER SATUSFACTION, YOUR FEEDBACK IS EXTREMELY IMPORTANT");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 860, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Enter your E-mail id");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 170, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Enter your user-id");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 170, 30));

        continue_togivefb.setBackground(new java.awt.Color(255, 255, 0));
        continue_togivefb.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        continue_togivefb.setText("Continue to give feedback");
        continue_togivefb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continue_togivefbActionPerformed(evt);
            }
        });
        jPanel1.add(continue_togivefb, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, 200, 30));

        jTextField6.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 0, 0));
        jTextField6.setText("DIRECTIONS :");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jTextField7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(204, 0, 0));
        jTextField7.setText("For each item please indicate your level of agreement with the following statement by choosing a score between 1 and 5.");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 760, -1));

        jTextField3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(204, 0, 51));
        jTextField3.setText("Heigher score indicates a stronger agreement with the statement.");
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));

        jTextField8.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(255, 0, 0));
        jTextField8.setText("1. POOR");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jTextField9.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(255, 0, 0));
        jTextField9.setText("2. FAIR");
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        jTextField10.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(255, 0, 0));
        jTextField10.setText("3. GOOD");
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));

        jTextField11.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(255, 0, 0));
        jTextField11.setText("4. VERY GOOD");
        jPanel1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, -1, -1));

        jTextField12.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(255, 0, 0));
        jTextField12.setText("5. EXCELLENT");
        jPanel1.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 15)); // NOI18N
        jLabel5.setText("1]    Are you satisfied with the existing library rules and regulations.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 15)); // NOI18N
        jLabel6.setText("2]   Availibity of textbooks, journals, magazines and news papers");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 15)); // NOI18N
        jLabel7.setText("3]    Quality of books and journals available");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 15)); // NOI18N
        jLabel8.setText("4]   Availability of library staff");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 15)); // NOI18N
        jLabel9.setText("5]   Co-operation of library staff");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 15)); // NOI18N
        jLabel10.setText("RESULT");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 630, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 1, 15)); // NOI18N
        jLabel11.setText("6]    Environment in library");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tempus Sans ITC", 1, 15)); // NOI18N
        jLabel12.setText("7]     Are you satisfied with the cataloguing and arrangement");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 1, 15)); // NOI18N
        jLabel13.setText("of books in the library");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 1, 15)); // NOI18N
        jLabel14.setText("8]    Are you satisfied with the available Reading space in the library");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 430, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tempus Sans ITC", 1, 15)); // NOI18N
        jLabel15.setText("9]    Are you able to make use of Xerox facility in the library");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tempus Sans ITC", 1, 15)); // NOI18N
        jLabel16.setText("10]   Are thr required number of title in your subject available");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 530, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tempus Sans ITC", 1, 15)); // NOI18N
        jLabel17.setText("in the library");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 560, -1, -1));

        overallrating.setBackground(new java.awt.Color(255, 255, 0));
        overallrating.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        overallrating.setText("OVERALL RATING");
        overallrating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overallratingActionPerformed(evt);
            }
        });
        jPanel1.add(overallrating, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 580, 200, 30));

        submit.setBackground(new java.awt.Color(255, 255, 0));
        submit.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 610, 140, 40));

        clear.setBackground(new java.awt.Color(255, 255, 0));
        clear.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        clear.setText("CLEAR");
        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 610, 140, 40));

        back.setBackground(new java.awt.Color(255, 255, 0));
        back.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 610, 140, 40));
        jPanel1.add(or, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 580, 200, 30));
        jPanel1.add(performance, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 630, 200, 30));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feedback/iiiiiiiiiiiiiiiiii.jpg"))); // NOI18N
        jLabel18.setText("jLabel18");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, -50, 280, 240));

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 70, 30));

        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 70, 30));

        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jTextField13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField13KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 80, 30));

        jTextField14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField14KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 460, 80, 30));

        jTextField15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField15KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 520, 80, 30));

        jTextField16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField16KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1056, 300, 70, 30));

        jTextField17.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField17KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1056, 360, 70, 30));

        jTextField18.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField18KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 420, 70, 30));

        jTextField19.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField19KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1056, 490, 70, 30));

        jTextField20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField20KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1056, 540, 70, 30));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feedback/llllllllllllllllllllllllll.jpg"))); // NOI18N
        jLabel19.setText("jLabel19");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1230, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void overallratingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overallratingActionPerformed
        // TODO add your handling code here:
        if(jTextField4.getText().isEmpty()||jTextField5.getText().isEmpty()||jTextField13.getText().isEmpty()||jTextField14.getText().isEmpty()||jTextField15.getText().isEmpty()||jTextField16.getText().isEmpty()||jTextField17.getText().isEmpty()||jTextField18.getText().isEmpty()||jTextField19.getText().isEmpty()||jTextField20.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"ENTER VALUES FOR ALL FIELDS");
        }  
        else
        {
            try
            {
              int a,b,c,d,e,f,g,h,i,j,result;
               a=Integer.parseInt(jTextField4.getText());
               b=Integer.parseInt(jTextField5.getText());
               c=Integer.parseInt(jTextField13.getText());
               d=Integer.parseInt(jTextField14.getText());
               e=Integer.parseInt(jTextField15.getText());
               f=Integer.parseInt(jTextField16.getText());
               g=Integer.parseInt(jTextField17.getText());
               h=Integer.parseInt(jTextField18.getText());
               i=Integer.parseInt(jTextField19.getText());
               j=Integer.parseInt(jTextField20.getText());
               result=a+b+c+d+e+f+g+h+i+j;
               or.setText(""+result);
               if(result<=10)
                   performance.setText("POOR");
               else if(result>10&&result<=20)
                   performance.setText("FAIR");
               else if(result>20&&result<=30)
                   performance.setText("GOOD");
               else if(result>30&&result<=40)
                   performance.setText("VERY GOOD");
               else if(result>40&&result<=50)
                    performance.setText("EXCELLENT");
               else if(result>50)
                    performance.setText("WRONG INPUT");      
            }
            catch(Exception e)
            {
              JOptionPane.showMessageDialog(null,e.toString());  
            }
        }
    }//GEN-LAST:event_overallratingActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        if(jTextField4.getText().isEmpty()||jTextField5.getText().isEmpty()||jTextField13.getText().isEmpty()||jTextField14.getText().isEmpty()||jTextField15.getText().isEmpty()||jTextField16.getText().isEmpty()||jTextField17.getText().isEmpty()||jTextField18.getText().isEmpty()||jTextField19.getText().isEmpty()||jTextField20.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"ENTER VALUES FOR ALL FIELDS");
        }  
        else
        {
            try         //insert intio library=library is the table name in services->tables->library table name
            {
               String url="jdbc:derby://localhost:1527/student";
                String user="vaishnavi";
                String pass="vaishu";
                Connection con=(Connection)DriverManager.getConnection(url,user,pass);
                Statement stmt=(Statement)con.createStatement();
                String query="insert into libraryresult(mail,uid,rating,result)values('"+jTextField1.getText()+"','"+jTextField2.getText()+"','"+or.getText()+"','"+performance.getText()+"')";
                stmt.execute(query);
                  JOptionPane.showMessageDialog(null,"FEEDBACK ACCEPTED");
            }
            catch(Exception e)
            {
              JOptionPane.showMessageDialog(null,e.toString());  
            }
        }
        
    }//GEN-LAST:event_submitActionPerformed

    private void continue_togivefbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continue_togivefbActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().isEmpty()||jTextField2.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"ENTER VALUES FOR ALL FIELDS");
        }
        else
        {
            String url="jdbc:derby://localhost:1527/student";
                    String user="vaishnavi";
                    String pass="vaishu";
                    String emailid,userid;
                    emailid=jTextField1.getText();
                    userid=jTextField2.getText();
                    try
                    {
                        PreparedStatement pst;
                        ResultSet rs=null;
                        Connection con=(Connection)DriverManager.getConnection(url,user,pass);
                        String query="select email,id from register where email=? and id=?";
                         pst=con.prepareStatement(query);
                        pst.setString(1,emailid);
                        pst.setString(2,userid);
                        rs=pst.executeQuery();
                        if(rs.next())
                        {
                          JOptionPane.showMessageDialog(null,"YOU CAN GIVE FEEDBACK");
                          jLabel5.setVisible(true);
                          jLabel6.setVisible(true);
                          jLabel7.setVisible(true);
                          jLabel8.setVisible(true);
                          jLabel9.setVisible(true);
                          jLabel10.setVisible(true);
                          jLabel11.setVisible(true);
                          jLabel12.setVisible(true);
                          jLabel13.setVisible(true);
                          jLabel14.setVisible(true);
                          jLabel15.setVisible(true);
                          jLabel16.setVisible(true);
                          jLabel17.setVisible(true);
                          jTextField6.setVisible(true);
                          jTextField7.setVisible(true);
                          jTextField3.setVisible(true);
                          jTextField8.setVisible(true);
                          jTextField9.setVisible(true);
                          jTextField10.setVisible(true);
                          jTextField11.setVisible(true);
                          jTextField12.setVisible(true);
                          jTextField4.setVisible(true);
                          jTextField5.setVisible(true);
                          jTextField13.setVisible(true);
                          jTextField14.setVisible(true);
                          jTextField15.setVisible(true);
                          jTextField16.setVisible(true);
                          jTextField17.setVisible(true);
                          jTextField18.setVisible(true);
                          jTextField19.setVisible(true);
                          jTextField20.setVisible(true);
                          or.setVisible(true);
                          performance.setVisible(true);
                          overallrating.setVisible(true);
                          submit.setVisible(true);
                          clear.setVisible(true);   
                        }
                    }
                    catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(null,e.toString()); 
                    }
        }
    }//GEN-LAST:event_continue_togivefbActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new student_choosetypes().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        // TODO add your handling code here:
        String ph=jTextField4.getText();
        int length= ph.length();
        char c=evt.getKeyChar();
        if(evt.getKeyChar()>='1'&&evt.getKeyChar()<='5'&&ph.length()<1||c==KeyEvent.VK_BACK_SPACE)
        {
            jTextField4.setEditable(true);
        }
        else
        {
             jTextField4.setEditable(false);
        }
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        // TODO add your handling code here:
        String ph=jTextField5.getText();
        int length= ph.length();
        char c=evt.getKeyChar();
        if(evt.getKeyChar()>='1'&&evt.getKeyChar()<='5'&&ph.length()<1||c==KeyEvent.VK_BACK_SPACE)
        {
            jTextField5.setEditable(true);
        }
        else
        {
             jTextField5.setEditable(false);
        }
    }//GEN-LAST:event_jTextField5KeyTyped

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField13KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField13KeyTyped
        // TODO add your handling code here:
        String ph=jTextField13.getText();
        int length= ph.length();
        char c=evt.getKeyChar();
        if(evt.getKeyChar()>='1'&&evt.getKeyChar()<='5'&&ph.length()<1||c==KeyEvent.VK_BACK_SPACE)
        {
            jTextField13.setEditable(true);
        }
        else
        {
             jTextField13.setEditable(false);
        }
    }//GEN-LAST:event_jTextField13KeyTyped

    private void jTextField14KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField14KeyTyped
        // TODO add your handling code here:
        String ph=jTextField14.getText();
        int length= ph.length();
        char c=evt.getKeyChar();
        if(evt.getKeyChar()>='1'&&evt.getKeyChar()<='5'&&ph.length()<1||c==KeyEvent.VK_BACK_SPACE)
        {
            jTextField14.setEditable(true);
        }
        else
        {
             jTextField14.setEditable(false);
        }
    }//GEN-LAST:event_jTextField14KeyTyped

    private void jTextField15KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField15KeyTyped
        // TODO add your handling code here:
        String ph=jTextField15.getText();
        int length= ph.length();
        char c=evt.getKeyChar();
        if(evt.getKeyChar()>='1'&&evt.getKeyChar()<='5'&&ph.length()<1||c==KeyEvent.VK_BACK_SPACE)
        {
            jTextField15.setEditable(true);
        }
        else
        {
             jTextField15.setEditable(false);
        }
    }//GEN-LAST:event_jTextField15KeyTyped

    private void jTextField16KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField16KeyTyped
        // TODO add your handling code here:
        String ph=jTextField16.getText();
        int length= ph.length();
        char c=evt.getKeyChar();
        if(evt.getKeyChar()>='1'&&evt.getKeyChar()<='5'&&ph.length()<1||c==KeyEvent.VK_BACK_SPACE)
        {
            jTextField16.setEditable(true);
        }
        else
        {
             jTextField16.setEditable(false);
        }
    }//GEN-LAST:event_jTextField16KeyTyped

    private void jTextField17KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField17KeyTyped
        // TODO add your handling code here:
        String ph=jTextField17.getText();
        int length= ph.length();
        char c=evt.getKeyChar();
        if(evt.getKeyChar()>='1'&&evt.getKeyChar()<='5'&&ph.length()<1||c==KeyEvent.VK_BACK_SPACE)
        {
            jTextField17.setEditable(true);
        }
        else
        {
             jTextField17.setEditable(false);
        }
    }//GEN-LAST:event_jTextField17KeyTyped

    private void jTextField18KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField18KeyTyped
        // TODO add your handling code here:
        String ph=jTextField18.getText();
        int length= ph.length();
        char c=evt.getKeyChar();
        if(evt.getKeyChar()>='1'&&evt.getKeyChar()<='5'&&ph.length()<1||c==KeyEvent.VK_BACK_SPACE)
        {
            jTextField18.setEditable(true);
        }
        else
        {
             jTextField18.setEditable(false);
        }
    }//GEN-LAST:event_jTextField18KeyTyped

    private void jTextField19KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField19KeyTyped
        // TODO add your handling code here:
        String ph=jTextField19.getText();
        int length= ph.length();
        char c=evt.getKeyChar();
        if(evt.getKeyChar()>='1'&&evt.getKeyChar()<='5'&&ph.length()<1||c==KeyEvent.VK_BACK_SPACE)
        {
            jTextField19.setEditable(true);
        }
        else
        {
             jTextField19.setEditable(false);
        }
    }//GEN-LAST:event_jTextField19KeyTyped

    private void jTextField20KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField20KeyTyped
        // TODO add your handling code here:
        String ph=jTextField20.getText();
        int length= ph.length();
        char c=evt.getKeyChar();
        if(evt.getKeyChar()>='1'&&evt.getKeyChar()<='5'&&ph.length()<1||c==KeyEvent.VK_BACK_SPACE)
        {
            jTextField20.setEditable(true);
        }
        else
        {
             jTextField20.setEditable(false);
        }
    }//GEN-LAST:event_jTextField20KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(library_feedbackform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(library_feedbackform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(library_feedbackform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(library_feedbackform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new library_feedbackform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton clear;
    private javax.swing.JButton continue_togivefb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField or;
    private javax.swing.JButton overallrating;
    private javax.swing.JTextField performance;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
