/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feedback;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.Random;

/**
 *
 * @author Lenovo
 */
public class staff_registration extends javax.swing.JFrame {

    /**
     * Creates new form staff_registration
     */
    public staff_registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        experience = new javax.swing.JTextField();
        mail = new javax.swing.JTextField();
        contact_no = new javax.swing.JTextField();
        register = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        back = new javax.swing.JButton();
        id_no = new javax.swing.JTextField();
        branch = new javax.swing.JComboBox<>();
        dept = new javax.swing.JComboBox<>();
        designation = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel1.setText("NEW STAFF REGISTRATION");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 300, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feedback/sun.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 490, 130));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 34, 630, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel4.setText("ID NUMBER");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 150, 20));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel5.setText("FIRST NAME");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 150, 20));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel6.setText("BRANCH");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 150, 20));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel7.setText("DEPARTMENT");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 150, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel8.setText("DESIGNATION");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 150, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel9.setText("EXPERIANCE");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 150, 20));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel10.setText("E-MAIL ID");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 150, 20));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel11.setText("CONTACT NUMBER");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 160, 20));

        fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fnameKeyPressed(evt);
            }
        });
        jPanel1.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 180, 30));
        jPanel1.add(experience, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 190, 30));
        jPanel1.add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 190, 30));

        contact_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contact_noKeyTyped(evt);
            }
        });
        jPanel1.add(contact_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 190, 30));

        register.setBackground(new java.awt.Color(255, 255, 0));
        register.setFont(new java.awt.Font("Tempus Sans ITC", 1, 15)); // NOI18N
        register.setText("REGISTER");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        jPanel1.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, 120, 40));

        clear.setBackground(new java.awt.Color(255, 255, 0));
        clear.setFont(new java.awt.Font("Tempus Sans ITC", 1, 15)); // NOI18N
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, 120, 40));

        back.setBackground(new java.awt.Color(255, 255, 0));
        back.setFont(new java.awt.Font("Tempus Sans ITC", 1, 15)); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, 120, 40));

        id_no.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                id_noMouseClicked(evt);
            }
        });
        jPanel1.add(id_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 180, 30));

        branch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT BRANCH", "Physics", "Mathematics", "Computer Science", "Statistics", "Electronics", "Data Science", "Economics", "Accountancy", "Marketing Management", "Buissiness Management", "Social Studies", "English", "Kannada", "Hindi", "English Litereature", "Psychology", "Sociology" }));
        jPanel1.add(branch, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 180, 30));

        dept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT DEPARTMENT", "Science", "Commerce", "Arts", " " }));
        jPanel1.add(dept, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 180, 30));

        designation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT DESIGNATION", "Principal", "Lecturer", "Associate Professor", "Assistant Professor", "Instructor", "Professor", "Research Instructor", "Research Professor", "Visiting Assistant Professor", "Visiting Associate Professor", "Councelor", "" }));
        jPanel1.add(designation, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 180, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feedback/features.jepg.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 460, 260));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feedback/LGT CLRS.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 941, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        if(fname.getText().isEmpty()||id_no.getText().isEmpty()||branch.getSelectedItem().toString().isEmpty()||dept.getSelectedItem().toString().isEmpty()||designation.getSelectedItem().toString().isEmpty()||mail.getText().isEmpty()||contact_no.getText().isEmpty()||experience.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"ENTER VALUES FOR ALL FIELDS" );
        }
        else
        {
            try
            {
             String url="jdbc:derby://localhost:1527/student";
                    String user="vaishnavi";
                    String pass="vaishu";
                    Connection con=(Connection)DriverManager.getConnection(url, user, pass);
                    Statement stmt=(Statement)con.createStatement();
                    String query="insert into staff(fname,id_no,branch,dept,designation,experience,mail,contact_no)values('"+fname.getText()+"','"+id_no.getText()+"','"+branch.getSelectedItem()+"','"+dept.getSelectedItem()+"','"+designation.getSelectedItem()+"','"+experience.getText()+"','"+mail.getText()+"','"+contact_no.getText()+"')";
                    stmt.execute(query);
                    JOptionPane.showMessageDialog(null,"Registered");
            }
        
            catch(Exception e)
            {
              JOptionPane.showMessageDialog(null,"sorry!...can not register");    
            }
    
        }
    }//GEN-LAST:event_registerActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        fname.setText("");
        id_no.setText("");
        branch.setSelectedItem("SELECT BRANCH");
        dept.setSelectedItem("SELECT DEPARTMENT");
        designation.setSelectedItem("SELECT DESIGNATION");
        experience.setText("");
        mail.setText("");
        contact_no.setText("");        
                
    }//GEN-LAST:event_clearActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new welcome().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void contact_noKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contact_noKeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
        
        String ph=contact_no.getText();
        int length=ph.length();
        c = evt.getKeyChar();
        if(evt.getKeyChar()>='0'&&evt.getKeyChar()<='9')
        {
            if(length<10)
            {
                contact_no.setEditable(true);
            }
            else
            {
                contact_no.setEditable(false);
            }
        }
    }//GEN-LAST:event_contact_noKeyTyped

    private void id_noMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_id_noMouseClicked
        // random id generator
        String str = "1234567890";
        Random rnd = new Random();
        StringBuilder sb = new StringBuilder(4);
        for(int i=0;i<4;i++)
        {
            sb.append(str.charAt(rnd.nextInt(str.length())));
        }
        String random=sb.toString();
        id_no.setText(random);
    }//GEN-LAST:event_id_noMouseClicked

    private void fnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnameKeyPressed
        // TO aacept only characters              
        char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||c==KeyEvent.VK_PERIOD)
        {
            fname.setEditable(true);
        }
        else
        {
            fname.setEditable(false);
        }
        
    }//GEN-LAST:event_fnameKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(staff_registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(staff_registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(staff_registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(staff_registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new staff_registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JComboBox<String> branch;
    private javax.swing.JButton clear;
    private javax.swing.JTextField contact_no;
    private javax.swing.JComboBox<String> dept;
    private javax.swing.JComboBox<String> designation;
    private javax.swing.JTextField experience;
    private javax.swing.JTextField fname;
    private javax.swing.JTextField id_no;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mail;
    private javax.swing.JButton register;
    // End of variables declaration//GEN-END:variables
}
